on: [push, pull_request]
name: Go Build

jobs:
  unit:
    runs-on: ubuntu-latest
    name: All
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: false
      - name: Build iptb
        run: make iptb
      - name: Build ipfslocal
        run: make ipfslocal
      - name: Build p2pdlocal
        run: make p2pdlocal
      - name: Build ipfsdocker
        run: make ipfsdocker
      - name: Build ipfsbrowser
        run: make ipfsbrowser
